### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by paulrogers909** [x4nth055/pythoncode-tutorials#9]
"ethical-hacking/keylogger/"

Have latest code version and currently the line with: 

`name = f"[{name.upper()}]"`

is causing a "SyntaxError: invalid syntax"

If I comment out the code above, I get:

"ImportError: No module named keyboard"

I have a virtual environment with the latest version of the keyboard package (0.13.4), I also ran the code in the terminal without the virtual environment.

Any tips on a fix?
Thanks

**Comment by x4nth055** [comment]
Hello,

The first error is raised because F-string is introduced in Python 3.6+, so you should use Python 3.6+ for most of the codes here.

Second, make sure you have installed the right keyboard module installed on your Python 3.6+ without the virtual environment using:
`pip3 install keyboard`

Here is the official repo for it:
https://github.com/boppreh/keyboard

Hope this can help!

**Comment by paulrogers909** [comment]
Thanks, 

Just before you replied I used "sudo python3", running now.

Thanks once again.
